# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Peeporun < Formula
  desc "A TUI hit counter for Dark Souls, with OBS overlay and theme support"
  homepage "https://github.com/cometpuppy/peeporun"
  version "0.2.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cometpuppy/peeporun/releases/download/v0.2.3/peeporun_darwin_amd64.tar.gz"
      sha256 "c0000ef27099cc03957a1cad0e50983ab741174154319bb46e672bdd03ab5eaf"

      define_method(:install) do
        bin.install "peeporun"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cometpuppy/peeporun/releases/download/v0.2.3/peeporun_darwin_arm64.tar.gz"
      sha256 "2d2c8d188c0532a9dd91cd5b31593975be54457d92c7c4d4d057215585f83e9d"

      define_method(:install) do
        bin.install "peeporun"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cometpuppy/peeporun/releases/download/v0.2.3/peeporun_linux_amd64.tar.gz"
      sha256 "50bf4079ad0c4718c97020191d7ceb96ac404933124faea121604d7b1b362fad"
      define_method(:install) do
        bin.install "peeporun"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cometpuppy/peeporun/releases/download/v0.2.3/peeporun_linux_arm64.tar.gz"
      sha256 "ebeeb639b3d5733aa598ef3d8240671d4a6fc98dd7880ab8833a14c24a743dd0"
      define_method(:install) do
        bin.install "peeporun"
      end
    end
  end

  test do
    system "#{bin}/peeporun", "--version"
  end
end
